
### Create User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "username":"test11",
    "password":"password",
    "createdAt":"2000-01-01 00:00:00",
    "updatedAt":"2000-01-01 00:00:00"
}

### Sign in
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "username":"test11",
    "password":"password"
}


### cached
GET  http://localhost:3000/auth/whoami



###sign out
POST  http://localhost:3000/auth/signout


### Find User by Id

Get http://localhost:3000/auth/12



### Get All
Get http://localhost:3000/auth



### Delete user
DELETE http://localhost:3000/auth/5




### patch user
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "username":"not me"
}



